# This is a basic workflow to help you get started with Actions

name: Package and Release Datapack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags: "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip datapack
        working-directory: capture_system
        run: |
          mkdir output
          zip -r ../output/capture_system.zip ./

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: output/capture_system.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
